Incorrect i2c is a headache
RIT-EVT/IMU pull request #4
Opened 2023-03-05 21:38 UTC by ActuallyZach

2023-03-06 22:17 UTC, mjmagee991 requested changes
There's some high-level design that needs some work, but the implementation looks great!

2023-03-06 22:17 UTC, mjmagee991 commented on CMakeLists.txt
>  # Add sources
On line 10, add `add_compile_definitions(USE_HAL_DRIVER)` to fix the compilation error you're getting from the build script.

2023-03-06 22:17 UTC, mjmagee991 commented on include/BNO055.hpp
> +#ifndef IMU_BNO055_HPP
The header guard should be above the includes

2023-03-06 22:17 UTC, mjmagee991 commented on include/BNO055.hpp
> +    BNO055(IO::I2C& i2C);
These methods need documentation

2023-03-06 22:17 UTC, mjmagee991 commented on include/BNO055.hpp
> +class BNO055 {
There should be a comment summarizing the class. This should also have a link to the datasheet and the Arduino code that a lot of it is based on

2023-03-06 22:17 UTC, mjmagee991 commented on include/BNO055.hpp
> +};
```suggestion
};

```

2023-03-06 22:17 UTC, mjmagee991 commented on include/BNO055.hpp
> +    EVT::core::IO::I2C& i2c;
```suggestion
    IO::I2C& i2c;
```

2023-03-06 22:17 UTC, mjmagee991 commented on include/IMU.hpp
> +    IMU(IO::I2C& i2C);
This method should have documented, and the `IMU` class should take and instance of `BNO055`, not `I2C`. Normally, we only pass the board class the objects that it's going to interface with, not the low-level communication protocols

2023-03-06 22:17 UTC, mjmagee991 commented on include/IMU.hpp
> +    void cycle();
This should be documented. Also, just following convention, we normally call the main loop function of a board `process()`.

2023-03-06 22:17 UTC, mjmagee991 commented on include/IMU.hpp
> +    BNO055 bno055;
Add a docstring for this

2023-03-06 22:17 UTC, mjmagee991 commented on src/IMU.cpp
> +    bno055.setup();
Even though you're modifying this method, still run this method in the constructor

2023-03-06 22:17 UTC, mjmagee991 commented on src/BNO055.cpp
> +IO::I2C::I2CStatus IMU::BNO055::getEuler(uint16_t& xBuffer, uint16_t& yBuffer, uint16_t& zBuffer) {
Modify these functions to take `int16_t&` instead of `uint16_t&` because from the outside perspective, they are really signed. You might have to do some weird stuff to get C++ not to screw with the value, but it should work

2023-03-06 22:17 UTC, mjmagee991 commented on targets/BNO055-Sample/main.cpp
> +#include <EVT/dev/Timer.hpp>
Even though it's obvious, add a comment to the beginning of this file explaining what it's for

2023-03-06 22:17 UTC, mjmagee991 commented on targets/CMakeLists.txt
> +add_subdirectory(DEV1-IMU)
```suggestion
add_subdirectory(DEV1-IMU)

```

2023-03-06 22:17 UTC, mjmagee991 commented on targets/BNO055-Sample/main.cpp
> +}
```suggestion
}

```

2023-03-06 22:17 UTC, mjmagee991 commented on src/BNO055.cpp
> +bool IMU::BNO055::setup() {
Both methods here need a lot of inline documentation explaining the weird I2C stuff that's going on and what each step is doing

2023-03-06 22:17 UTC, mjmagee991 commented on src/BNO055.cpp
> +IO::I2C::I2CStatus IMU::BNO055::getGyroscope(uint16_t& xBuffer, uint16_t& yBuffer, uint16_t& zBuffer) {
You could make 1 private method that you pass these parameters and an address into, so you don't have the same method 3 times

2023-03-06 22:17 UTC, mjmagee991 commented on src/IMU.cpp
> +}
```suggestion
}

```

2023-03-06 22:17 UTC, mjmagee991 commented on src/IMU.cpp
>  namespace IMU {
```suggestion
namespace IMU {

```

2023-03-06 22:17 UTC, mjmagee991 commented on src/IMU.cpp
> +    bno055.getEuler(eulerX, eulerY, eulerZ);
It's a little out of scope for this task, but while you're at it, you could just pass the CAN values like `vectorY[0]` in right here to get it writing to CAN. That's all we really need to get IMU main ready to go

2023-03-07 00:11 UTC, AarC10 requested changes

2023-03-07 00:11 UTC, AarC10 commented on src/BNO055.cpp
> +IO::I2C::I2CStatus IMU::BNO055::getLinearAccel(uint16_t& xBuffer, uint16_t& yBuffer, uint16_t& zBuffer) {
```suggestion
IO::I2C::I2CStatus IMU::BNO055::getLinearAccel(uint16_t* xBuffer, uint16_t* yBuffer, uint16_t* zBuffer) {
```

2023-03-07 00:11 UTC, AarC10 commented on src/BNO055.cpp
> +IO::I2C::I2CStatus IMU::BNO055::getAccelerometer(uint16_t& xBuffer, uint16_t& yBuffer, uint16_t& zBuffer) {
```suggestion
IO::I2C::I2CStatus IMU::BNO055::getAccelerometer(uint16_t* xBuffer, uint16_t* yBuffer, uint16_t* zBuffer) {
```

2023-03-07 00:11 UTC, AarC10 commented on src/IMU.cpp
> +    uint16_t gyroX, gyroY, gyroZ;
Put these on separate lines

2023-03-07 00:11 UTC, AarC10 commented on src/IMU.cpp
> +    uint16_t linearAccelX, linearAccelY, linearAccelZ;
Separate lines

2023-03-07 00:11 UTC, AarC10 commented on targets/BNO055-Sample/main.cpp
> +        uint16_t eulerX, eulerY, eulerZ;
Separate lines

2023-03-07 00:11 UTC, AarC10 commented on targets/DEV1-IMU/main.cpp
> +        time::wait(1000);
Is there a good reason for modifying the delay?

2023-03-07 00:51 UTC, ActuallyTaylor commented on targets/DEV1-IMU/main.cpp
> +        time::wait(1000);
Oops no, that was just for debugging

2023-03-07 01:37 UTC, mjmagee991 requested changes
Just a couple more questions about the implementation

2023-03-07 01:37 UTC, mjmagee991 commented on include/BNO055.hpp
> + * A driver for the BNO055 orientation sensor.
These comments are only necessary for target main files

2023-03-07 01:37 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * Initializer for a BNO55 sensor.
```suggestion
     * Initializer for a BNO055 sensor.
```

2023-03-07 01:37 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * Sends all of the required i2c commands too initialize the i2c so it actually sends data.
```suggestion
     * Sends all of the required i2c commands too initialize the i2c so it actually sends data.
     *
```

2023-03-07 01:37 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * Internally calls `fetchData`
You don't need to describe the internal operation of the method in the documentation

2023-03-07 01:37 UTC, mjmagee991 commented on include/BNO055.hpp
> +    * @param xBuffer a buffer to store the x data in.
I'm not sure why the autoformatter didn't fix this indentation but all the `*` should be in a column

2023-03-07 01:37 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * @param zBuffer a buffer to store the z data in.
```suggestion
     * @param zBuffer a buffer to store the z data in.
     *
```

2023-03-07 01:37 UTC, mjmagee991 commented on include/IMU.hpp
> +    IMU(BNO055& bnu055);
```suggestion
    IMU(BNO055& bno055);
```

2023-03-07 01:37 UTC, mjmagee991 commented on src/BNO055.cpp
> + * This function is a doozie, most of the issues with it come from the fact that the BNO055 does not use standard i2c.
You should add an `@return`

2023-03-07 01:37 UTC, mjmagee991 commented on src/BNO055.cpp
> +    // First write an empty i2c command to the device.
Add a TODO to check if this succeeds, so we can determine if the BNO055 is connected

2023-03-07 18:42 UTC, mjmagee991 requested changes
Just some more formatting and documentation changes

2023-03-07 18:42 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * Sends all of the required i2c commands too initialize the i2c so it actually sends data.
```suggestion
     * Sends all of the required i2c commands to initialize the chip
```

2023-03-07 18:42 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * @return a boolean value if the setup succeeded.
```suggestion
     * @return whether the setup succeeded.
```

2023-03-07 18:42 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * @return
The second `@return` should be deleted, and the first should be moved down

2023-03-07 18:42 UTC, mjmagee991 commented on include/BNO055.hpp
> +     * Fetch the gyroscope data from the BNO055.
You probably don't need to say "from the BNO055" for all these comments

2023-03-07 18:42 UTC, mjmagee991 commented on include/IMU.hpp
> +     * @param bnu055 the bno055 device that the IMU pulls data from.
```suggestion
     * @param bno055 the bno055 device that the IMU pulls data from.
```

2023-03-10 00:02 UTC, ActuallyZach commented
![](https://github.trello.services/images/mini-trello-icon.png) [IMU Main](https://trello.com/c/R1WkGG5f/133-imu-main)

2023-03-10 00:31 UTC, ActuallyZach commented
![](https://github.trello.services/images/mini-trello-icon.png) [IMU Driver](https://trello.com/c/4zQZxxDG/43-imu-driver)

2023-03-20 21:22 UTC, mjmagee991 approved these changes
Nice work!

2023-03-20 21:58 UTC, mjmagee991 requested changes
Issues with the slave address

2023-03-20 21:58 UTC, mjmagee991 commented on include/BNO055.hpp
> +    static constexpr uint8_t I2C_SLAVE_ADDR = 0x28;
This should be passed in as a constructor parameter

2023-03-20 21:58 UTC, mjmagee991 commented on src/BNO055.cpp
> +    IO::I2C::I2CStatus writeStatus = i2c.write(0x28, lowestAddress);
These shouldn't be hardcoded to `0x28`

2023-03-20 22:18 UTC, AarC10 commented on include/IMU.hpp
> +    int16_t vectorZValues[4] = {0, 0, 0, 0};
For future reference, just doing {} can automatically initialize them to zero

2023-03-20 22:19 UTC, AarC10 approved these changes

2023-03-20 23:06 UTC, Ethangirard62 approved these changes

2023-03-21 01:42 UTC, mjmagee991 approved these changes
Nice work

2023-03-21 01:42 UTC, merged