what did the Doppelganger say? IMU
RIT-EVT/IMU pull request #7
Opened 2024-01-30 01:58 UTC by DiegoLHendrix

2024-02-03 16:22 UTC, pro-sper approved these changes
It looks correct to me

2024-02-08 23:20 UTC, mjmagee991 requested changes
Some cleanup to do

2024-02-08 23:20 UTC, mjmagee991 commented on include/IMU.hpp
> +        MANDATORY_IDENTIFICATION_ENTRIES_1000_1014,
Add comments to the dictionary similar to the examples

2024-02-08 23:20 UTC, mjmagee991 commented on include/IMU.hpp
> +        DATA_LINK_START_KEY_21XX(0x00, 0x04),
@ActuallyTaylor Are these data links set up right?

2024-02-08 23:20 UTC, mjmagee991 commented on targets/DEV1-IMU/main.cpp
> +    auto* queue = (EVT::core::types::FixedQueue<CANOPEN_QUEUE_SIZE, IO::CANMessage>*) priv;
Change this function back to be the way it was initially

2024-02-08 23:20 UTC, mjmagee991 commented on targets/DEV1-IMU/main.cpp
> +IO::UART& uart = IO::getUART<IO::Pin::UART_TX, IO::Pin::UART_RX>(9600);
Don't use a global UART instance. Use the logger

2024-02-08 23:20 UTC, mjmagee991 commented on targets/DEV1-IMU/main.cpp
> +//setup a TPDO event handler to print the raw TPDO message when sending
Delete this function. It's not necessary for main code

2024-02-10 22:01 UTC, mjmagee991 approved these changes
Looks great

2024-02-13 00:04 UTC, merged